### ISSUE TITLE
[Help] Try Linksbypasser

### ISSUE THREAD

**Issue by yasawibu** [evetaku/tester#1]
Hi @evetaku 
I make a project like Adsbypasser.
Can you help me give an information about new link?
Thanks.

Link: https://github.com/yasawibu/linksbypasser

**Comment by evetaku** [comment]
@yasawibu from country ?
i look all link dominated from indo ?

**Comment by yasawibu** [comment]
@evetaku 
I am from indonesia.
Sorry for late reply.
I did not see the notification 😭
